// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service.proto

package org.fbichat.stub;

public interface NoneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service.None)
    com.google.protobuf.MessageOrBuilder {
}
