// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service.proto

package org.fbichat.stub;

public interface ReportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service.Report)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string suspectWords = 1;</code>
   * @return A list containing the suspectWords.
   */
  java.util.List<String>
      getSuspectWordsList();
  /**
   * <code>repeated string suspectWords = 1;</code>
   * @return The count of suspectWords.
   */
  int getSuspectWordsCount();
  /**
   * <code>repeated string suspectWords = 1;</code>
   * @param index The index of the element to return.
   * @return The suspectWords at the given index.
   */
  String getSuspectWords(int index);
  /**
   * <code>repeated string suspectWords = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the suspectWords at the given index.
   */
  com.google.protobuf.ByteString
      getSuspectWordsBytes(int index);

  /**
   * <code>string content = 2;</code>
   * @return The content.
   */
  String getContent();
  /**
   * <code>string content = 2;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string from = 3;</code>
   * @return The from.
   */
  String getFrom();
  /**
   * <code>string from = 3;</code>
   * @return The bytes for from.
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>string to = 4;</code>
   * @return The to.
   */
  String getTo();
  /**
   * <code>string to = 4;</code>
   * @return The bytes for to.
   */
  com.google.protobuf.ByteString
      getToBytes();

  /**
   * <code>string date = 5;</code>
   * @return The date.
   */
  String getDate();
  /**
   * <code>string date = 5;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
