// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service.proto

package org.fbichat.stub;

import java.util.List;

/**
 * Protobuf type {@code service.Report}
 */
public final class Report extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service.Report)
        ReportOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Report.newBuilder() to construct.
  private Report(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Report() {
    suspectWords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    content_ = "";
    from_ = "";
    to_ = "";
    date_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Report();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Report(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              suspectWords_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            suspectWords_.add(s);
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            content_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            from_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            to_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            date_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        suspectWords_ = suspectWords_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ServiceProto.internal_static_service_Report_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ServiceProto.internal_static_service_Report_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Report.class, Report.Builder.class);
  }

  public static final int SUSPECTWORDS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList suspectWords_;
  /**
   * <code>repeated string suspectWords = 1;</code>
   * @return A list containing the suspectWords.
   */
  public com.google.protobuf.ProtocolStringList
      getSuspectWordsList() {
    return suspectWords_;
  }
  /**
   * <code>repeated string suspectWords = 1;</code>
   * @return The count of suspectWords.
   */
  public int getSuspectWordsCount() {
    return suspectWords_.size();
  }
  /**
   * <code>repeated string suspectWords = 1;</code>
   * @param index The index of the element to return.
   * @return The suspectWords at the given index.
   */
  public String getSuspectWords(int index) {
    return suspectWords_.get(index);
  }
  /**
   * <code>repeated string suspectWords = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the suspectWords at the given index.
   */
  public com.google.protobuf.ByteString
      getSuspectWordsBytes(int index) {
    return suspectWords_.getByteString(index);
  }

  public static final int CONTENT_FIELD_NUMBER = 2;
  private volatile Object content_;
  /**
   * <code>string content = 2;</code>
   * @return The content.
   */
  @Override
  public String getContent() {
    Object ref = content_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <code>string content = 2;</code>
   * @return The bytes for content.
   */
  @Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    Object ref = content_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FROM_FIELD_NUMBER = 3;
  private volatile Object from_;
  /**
   * <code>string from = 3;</code>
   * @return The from.
   */
  @Override
  public String getFrom() {
    Object ref = from_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      from_ = s;
      return s;
    }
  }
  /**
   * <code>string from = 3;</code>
   * @return The bytes for from.
   */
  @Override
  public com.google.protobuf.ByteString
      getFromBytes() {
    Object ref = from_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      from_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TO_FIELD_NUMBER = 4;
  private volatile Object to_;
  /**
   * <code>string to = 4;</code>
   * @return The to.
   */
  @Override
  public String getTo() {
    Object ref = to_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      to_ = s;
      return s;
    }
  }
  /**
   * <code>string to = 4;</code>
   * @return The bytes for to.
   */
  @Override
  public com.google.protobuf.ByteString
      getToBytes() {
    Object ref = to_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      to_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATE_FIELD_NUMBER = 5;
  private volatile Object date_;
  /**
   * <code>string date = 5;</code>
   * @return The date.
   */
  @Override
  public String getDate() {
    Object ref = date_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      date_ = s;
      return s;
    }
  }
  /**
   * <code>string date = 5;</code>
   * @return The bytes for date.
   */
  @Override
  public com.google.protobuf.ByteString
      getDateBytes() {
    Object ref = date_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      date_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < suspectWords_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, suspectWords_.getRaw(i));
    }
    if (!getContentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
    }
    if (!getFromBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, from_);
    }
    if (!getToBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, to_);
    }
    if (!getDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, date_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < suspectWords_.size(); i++) {
        dataSize += computeStringSizeNoTag(suspectWords_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getSuspectWordsList().size();
    }
    if (!getContentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
    }
    if (!getFromBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, from_);
    }
    if (!getToBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, to_);
    }
    if (!getDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, date_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Report)) {
      return super.equals(obj);
    }
    Report other = (Report) obj;

    if (!getSuspectWordsList()
        .equals(other.getSuspectWordsList())) return false;
    if (!getContent()
        .equals(other.getContent())) return false;
    if (!getFrom()
        .equals(other.getFrom())) return false;
    if (!getTo()
        .equals(other.getTo())) return false;
    if (!getDate()
        .equals(other.getDate())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSuspectWordsCount() > 0) {
      hash = (37 * hash) + SUSPECTWORDS_FIELD_NUMBER;
      hash = (53 * hash) + getSuspectWordsList().hashCode();
    }
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (37 * hash) + FROM_FIELD_NUMBER;
    hash = (53 * hash) + getFrom().hashCode();
    hash = (37 * hash) + TO_FIELD_NUMBER;
    hash = (53 * hash) + getTo().hashCode();
    hash = (37 * hash) + DATE_FIELD_NUMBER;
    hash = (53 * hash) + getDate().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Report parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Report parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Report parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Report parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Report parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Report parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Report parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Report parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Report parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Report parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Report parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Report parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Report prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code service.Report}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service.Report)
          ReportOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ServiceProto.internal_static_service_Report_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ServiceProto.internal_static_service_Report_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Report.class, Report.Builder.class);
    }

    // Construct using org.fbichat.Report.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      suspectWords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      content_ = "";

      from_ = "";

      to_ = "";

      date_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ServiceProto.internal_static_service_Report_descriptor;
    }

    @Override
    public Report getDefaultInstanceForType() {
      return Report.getDefaultInstance();
    }

    @Override
    public Report build() {
      Report result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Report buildPartial() {
      Report result = new Report(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        suspectWords_ = suspectWords_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.suspectWords_ = suspectWords_;
      result.content_ = content_;
      result.from_ = from_;
      result.to_ = to_;
      result.date_ = date_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Report) {
        return mergeFrom((Report)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Report other) {
      if (other == Report.getDefaultInstance()) return this;
      if (!other.suspectWords_.isEmpty()) {
        if (suspectWords_.isEmpty()) {
          suspectWords_ = other.suspectWords_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureSuspectWordsIsMutable();
          suspectWords_.addAll(other.suspectWords_);
        }
        onChanged();
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        onChanged();
      }
      if (!other.getFrom().isEmpty()) {
        from_ = other.from_;
        onChanged();
      }
      if (!other.getTo().isEmpty()) {
        to_ = other.to_;
        onChanged();
      }
      if (!other.getDate().isEmpty()) {
        date_ = other.date_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Report parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Report) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList suspectWords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureSuspectWordsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        suspectWords_ = new com.google.protobuf.LazyStringArrayList(suspectWords_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string suspectWords = 1;</code>
     * @return A list containing the suspectWords.
     */
    public com.google.protobuf.ProtocolStringList
        getSuspectWordsList() {
      return suspectWords_.getUnmodifiableView();
    }
    /**
     * <code>repeated string suspectWords = 1;</code>
     * @return The count of suspectWords.
     */
    public int getSuspectWordsCount() {
      return suspectWords_.size();
    }
    /**
     * <code>repeated string suspectWords = 1;</code>
     * @param index The index of the element to return.
     * @return The suspectWords at the given index.
     */
    public String getSuspectWords(int index) {
      return suspectWords_.get(index);
    }
    /**
     * <code>repeated string suspectWords = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the suspectWords at the given index.
     */
    public com.google.protobuf.ByteString
        getSuspectWordsBytes(int index) {
      return suspectWords_.getByteString(index);
    }
    /**
     * <code>repeated string suspectWords = 1;</code>
     * @param index The index to set the value at.
     * @param value The suspectWords to set.
     * @return This builder for chaining.
     */
    public Builder setSuspectWords(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSuspectWordsIsMutable();
      suspectWords_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string suspectWords = 1;</code>
     * @param value The suspectWords to add.
     * @return This builder for chaining.
     */
    public Builder addSuspectWords(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSuspectWordsIsMutable();
      suspectWords_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string suspectWords = 1;</code>
     * @param values The suspectWords to add.
     * @return This builder for chaining.
     */
    public Builder addAllSuspectWords(
        Iterable<String> values) {
      ensureSuspectWordsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, suspectWords_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string suspectWords = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuspectWords() {
      suspectWords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string suspectWords = 1;</code>
     * @param value The bytes of the suspectWords to add.
     * @return This builder for chaining.
     */
    public Builder addSuspectWordsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureSuspectWordsIsMutable();
      suspectWords_.add(value);
      onChanged();
      return this;
    }

    private Object content_ = "";
    /**
     * <code>string content = 2;</code>
     * @return The content.
     */
    public String getContent() {
      Object ref = content_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string content = 2;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string content = 2;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string content = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }
    /**
     * <code>string content = 2;</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      content_ = value;
      onChanged();
      return this;
    }

    private Object from_ = "";
    /**
     * <code>string from = 3;</code>
     * @return The from.
     */
    public String getFrom() {
      Object ref = from_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        from_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string from = 3;</code>
     * @return The bytes for from.
     */
    public com.google.protobuf.ByteString
        getFromBytes() {
      Object ref = from_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string from = 3;</code>
     * @param value The from to set.
     * @return This builder for chaining.
     */
    public Builder setFrom(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      from_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string from = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrom() {
      
      from_ = getDefaultInstance().getFrom();
      onChanged();
      return this;
    }
    /**
     * <code>string from = 3;</code>
     * @param value The bytes for from to set.
     * @return This builder for chaining.
     */
    public Builder setFromBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      from_ = value;
      onChanged();
      return this;
    }

    private Object to_ = "";
    /**
     * <code>string to = 4;</code>
     * @return The to.
     */
    public String getTo() {
      Object ref = to_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        to_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string to = 4;</code>
     * @return The bytes for to.
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      Object ref = to_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string to = 4;</code>
     * @param value The to to set.
     * @return This builder for chaining.
     */
    public Builder setTo(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      to_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string to = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTo() {
      
      to_ = getDefaultInstance().getTo();
      onChanged();
      return this;
    }
    /**
     * <code>string to = 4;</code>
     * @param value The bytes for to to set.
     * @return This builder for chaining.
     */
    public Builder setToBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      to_ = value;
      onChanged();
      return this;
    }

    private Object date_ = "";
    /**
     * <code>string date = 5;</code>
     * @return The date.
     */
    public String getDate() {
      Object ref = date_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        date_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string date = 5;</code>
     * @return The bytes for date.
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string date = 5;</code>
     * @param value The date to set.
     * @return This builder for chaining.
     */
    public Builder setDate(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      date_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string date = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDate() {
      
      date_ = getDefaultInstance().getDate();
      onChanged();
      return this;
    }
    /**
     * <code>string date = 5;</code>
     * @param value The bytes for date to set.
     * @return This builder for chaining.
     */
    public Builder setDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      date_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    public void setSuspectWords(List<String> suspectWords) {
    }


    // @@protoc_insertion_point(builder_scope:service.Report)
  }

  // @@protoc_insertion_point(class_scope:service.Report)
  private static final Report DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Report();
  }

  public static Report getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Report>
      PARSER = new com.google.protobuf.AbstractParser<Report>() {
    @Override
    public Report parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Report(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Report> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Report> getParserForType() {
    return PARSER;
  }

  @Override
  public Report getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

